FROM iron/go:dev
WORKDIR /app
ENV SRC_DIR=/go/src/github.com/hiteshsethi/go-reader-writer/
# Add the source code:
ADD . $SRC_DIR
RUN cd $SRC_DIR; go build -o myapp writer/main.go; cp myapp /app/
ENTRYPOINT ["./myapp"]